name: Release on Tag

on:
  # push:
  #   tags:
  #     - 'v*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm build

      - name: Generate Package
        run: pnpm package

      - name: Validate if prerelease
        id: prerelease
        run: |
          if [[ "${{ github.ref_name }}" == *-* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          allowUpdates: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ steps.prerelease.outputs.is_prerelease }}
          artifacts: './package/system.json ./package/zombicide-chronicles-${{ github.ref_name }}.zip'
          body: |
            ## Changes in this release
            See [CHANGELOG](./CHANGELOG.md) for details.
