name: Validate Version

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get current PR version with prefix
        id: current_version
        run: |
          VERSION=v$(jq -r .version package.json)
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get latest tag
        id: latest_version
        run: |
          LATEST=$(git tag --sort=-v:refname | head -n1)
          echo "latest_version=$LATEST" >> $GITHUB_OUTPUT

      - name: Semver Compare
        id: semver_compare
        uses: samcarswell/semver-compare-action@1.1
        with:
          left-semver: ${{ steps.latest_version.outputs.latest_version }}
          right-semver: ${{ steps.current_version.outputs.current_version }}

      - name: Validate version is greater than latest
        run: |
          COMPARE=${{ steps.semver_compare.outputs.compare-value }}
          echo "Compare value: $COMPARE"
          if [ "$COMPARE" -ne -1 ]; then
            echo "ERROR: PR version must be greater than latest tag!"
            exit 1
          fi
